version: '2'
services:
  web:
    image: nuanxinqing123/home_navigation:latest
    volumes:
      - $PWD/conf:/conf
      - $PWD/img:/img
    ports:
      - "0.0.0.0:8082:8100"
    restart: unless-stopped